### ISSUE TITLE
V6.2.5版问题反馈

### ISSUE THREAD

**Issue by LZX284** [LZX284/Auto.Js#1]

**Comment by LZX284** [comment]
@alphaerp 迁移到这里了，目前6.2.5版源码尚未上传完成，暂时只有本地编译的APP是最新的……

**Comment by LZX284** [comment]
@alphaerp 找到 ACTION 编译失败的原因了，APK签名的密钥等需要自己单独设置，方法是在你自己Fork的仓库的 Settings- Secrets 中创建所需的几个环境变量：
> ${{ secrets.ISIGNING_KEY }}
> ${{ secrets.IALIAS }}
> ${{ secrets.IKEY_STORE_PASSWORD }}
> {{ secrets.IKEY_PASSWORD }}
> ${{ secrets.ASIGNING_KEY }}
> ${{ secrets.AALIAS }}
> ${{ secrets.AKEY_STORE_PASSWORD }}
> ${{ secrets.AKEY_PASSWORD }}

**Comment by alphaerp** [comment]
我能加你的联系方式吗？
