### ISSUE TITLE
大佬，最新的6.2.5版，进入“布局层次分析”还是无法返回，非得重启手机

### ISSUE THREAD

**Issue by lnxcyq** [LZX284/Auto.Js#2]

**Comment by agandab** [comment]
me too.

**Comment by LZX284** [comment]
@lnxcyq  @agandab  
[V6.2.5α](https://github.com/LZX284/Auto.Js/releases/tag/6.2.5%CE%B1) 
点击或长按界面元素弹出菜单，里面有一个 退出 选项，点击就可以关闭了；
另外，维护不易，如果觉得好用的话希望可以帮忙给这个项目点个 Star ☆

**Comment by LZX284** [comment]
@lnxcyq  @agandab  [tiyo](https://github.com/tiyo)
[V6.2.5α](https://github.com/LZX284/Auto.Js/releases/tag/6.2.5%CE%B1) 
点击或长按界面元素弹出菜单，里面有一个 退出 选项，点击就可以关闭了；

**Comment by LZX284** [comment]
@lnxcyq  @agandab  @tiyo 
[V6.2.5α](https://github.com/LZX284/Auto.Js/releases/tag/6.2.5%CE%B1) 
点击或长按界面元素弹出菜单，里面有一个 退出 选项，点击就可以关闭了；

**Comment by agandab** [comment]
问题解决了！希望你一直坚持下去！你的版本OCR速度是最快的，非常丝滑！

**Comment by LZX284** [comment]
> 问题解决了！希望你一直坚持下去！你的版本OCR速度是最快的，非常丝滑！

感谢支持，非常感谢！
